### ISSUE TITLE
typeof(GeofenceService): GeofenceService not found, should I use GeofenceLocationService instead?

### ISSUE THREAD

**Issue by aunanue** [domaven/xamarin-plugins#2]
AppContext.StopService(new Intent(AppContext, typeof(GeofenceService)));
this raises error on GeofenceService not found.

Should I use GeofenceLocationService instead? if so it would be great to update the sample project

**Comment by rdelrosario** [comment]
Is GeofenceService look for it on the PCL project on Helpers folder.
