### ISSUE TITLE
Object reference not set to an instance of an object: GeofenceTransitionsItentService.cs:52

### ISSUE THREAD

**Issue by aunanue** [domaven/xamarin-plugins#3]
When the App is running, I turn off the "Location" of the device, the public void OnError(string error) event of the IGeofenceListener is executed but after that I receive an "Object reference not set to an instance of an object: GeofenceTransitionsItentService.cs:52" error and the App crashes.

**Comment by rdelrosario** [comment]
Let me know if is fixed now, Just released a new version that handles location permission errors
