### ISSUE TITLE
notification with app closed don't work

### ISSUE THREAD

**Issue by a-iafrate** [domaven/xamarin-plugins#5]
I have try to implement notification when the app is close.
I have used your example.
inserted service class, created on startup and add permission but when i move with app closed nothing appear, if i open the app notification is send

Thanks for your beautiful library :D

**Comment by rdelrosario** [comment]
Hi
Is this on Android? Did you start the GeofenceService?

**Comment by rdelrosario** [comment]
Confirmed works with app closed.
