### ISSUE TITLE
Project and namespace with "-"

### ISSUE THREAD

**Issue by schorke** [domaven/xamarin-plugins#7]
Hi,

I found an issue when adding your Geofence plugin to a project with "-" in it. I use it in a PCL and error found when compiling the .Droid project :

`Tool exited with code: 1. Output: obj/Debug/android/manifest/AndroidManifest.xml:36: Tag <action> attribute name has invalid character '-'.` and line 36: `<action android:name="com.test.test-1.test-1.ACTION_RECEIVE_GEOFENCE" />`

Maybe you can add this in your README file with 

> The package name of your Android aplication must start with lower case 

Thanks for this very useful plugin 👍

**Comment by rdelrosario** [comment]
This note is already on the readme on Android specifics.

**Comment by schorke** [comment]
No, it is not. All you said in the Android specifics is to have a package name starting with lower case:

> The package name of your Android aplication must start with lower case or you will get the build error: Installation error: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED

This is not what I said, I said there's an issue with the hyphen character in the package name.

**Comment by rdelrosario** [comment]
Oh i see. Updating the readme

**Comment by schorke** [comment]
Nice, thank you! :+1:
